rft: drivers/can/can_mcan.c, can_mcan_priv.h fix: __SIZEOF_LONG__, __SIZEOF_LONG_LONG__ in sys/util.h should be size of bytes not bits !!! fix: LSB_GET in sys/util.h due to error C4146: unary minus operator applied to unsigned type, result still unsigned